# Builds using maven
# Pass the arguments you wish to run to maven_commands variable, default command will be mvn install
---
name: Maven

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    strategy:
      matrix:
        java: [1.8]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      maven_commands: install # default is install
      artifact_dir: target/*.(sh|txt)
    steps:
      - uses: actions/checkout@v2
      - name: move file
        run: |
          mkdir target
          cp download.sh target
          cp pom.xml target
          cp LICENSE.txt target
      - name: Upload artifacts
        if: matrix.os == 'ubuntu-latest' && matrix.java == '1.8'
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          if-no-files-found: error
          retention-days: 1
          path: ${{ env.artifact_dir }}
  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags')
    env:
      publishing_target: github # default is github
    steps:
      - name: Download artifacts from build
        uses: actions/download-artifact@v2
      - name: List artifacts
        run: ls -R
      - name: Upload binaries to release
        if: ${{ env.publishing_target }} == 'github'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
